### ISSUE TITLE
[Data Collection] Error: The file is not a crash dump

### ISSUE THREAD

**Issue by amrmahdi** [cshung/StringDedupAnalyzer#4]
Following the data collection instructions, and attempting to run the tool on the dump collected, yields the following error:

```
Unhandled exception. System.IO.InvalidDataException: The file is not a crash dump
   at Microsoft.Diagnostics.Runtime.DbgEngDataReader..ctor(String dumpFile)
   at Microsoft.Diagnostics.Runtime.DataTarget.LoadCrashDump(String path)
   at DumpStrings.Program.Main(String[] args)
```

Dump is collected from a .NET Core 3.0 process running in an ubuntu container on kubernets.

**Comment by cshung** [comment]
Fixed in #5
